#!/bin/bash
#set -x

#export GITDEBUG=go
#g: git commands
#o: output of git commands
#c: callstack when invoking git commands

export OREF_SIZE=500000
export CCCTERM_SIZE=120x40
#export CCCTERM_INHERIT=yes

exec gitnav.exe "$@" | tee log-gitnav

