#!/bin/bash
set -x

REMOTE_HOST=as
REMOTE_PATH=/home/vermes/git/ccc3.git
REMOTE_URL=ssh://vermes@$REMOTE_HOST$REMOTE_PATH
REMOTE_NAME=as_bare

# A remote szerverbe be-ssh-zunk, és létrehozzuk a bare repót:

ssh $REMOTE_HOST "git init --bare $REMOTE_PATH"

# A lokális repóban létrehozzuk a remote definíciót,
# ha ez megvan, akkor az URL helyett a rövid remote nevet
# használhatjuk. Több remote is lehet, és akármilyen neve 
# lehet a remoteoknak.  Egy remote meghatároz egy URL-t.

git remote add  $REMOTE_NAME $REMOTE_URL

# Most van a .git/config-ban egy uj remote szekciónk.

git push $REMOTE_NAME master

